name: Check generated build

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  generated-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run check:build
